version: "3.0"
services:
  web:
    image: egorpr0/abserver_rpi:latest
    command: bash start.sh
    volumes:
      - ".:/usr/src/app"
      - type: bind
        source: "/dev/"
        target: "/dev/"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    links:
      - mariadb
      - redis
      # - webpacker
    privileged: true

  #webpacker:
  #  image: egorpr0/abserver_rpi:latest
  #  environment:
  #    - NODE_OPTIONS=--max_old_space_size=4096
  #    - NODE_ENV=development
  #    - RAILS_ENV=development
  #    - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  #  command: ./app/bin/webpack-dev-server --inline true
  #  ports:
  #    - 3035:3035
  #  volumes:
  #    - .:/app

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
