development:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_URL") { "localhost" } %>:6379/1
  channel_prefix: smart_telesope_production

test:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_URL") { "localhost" } %>:6379/1
  channel_prefix: smart_telesope_production

production:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_URL") { "localhost" } %>:6379/1
  channel_prefix: smart_telesope_production
